<?xml version="1.0" encoding="utf-8"?><Database Name="BANHANG" Class="QuanLySachDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.163.16.87;Initial Catalog=BANHANG;User ID=laptrinhweb" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BANHANGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DANHMUCSP" Member="DANHMUCSPs">
    <Type Name="DANHMUCSP">
      <Column Name="IdDanhMuc" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HienThi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DANHMUCSP_SANPHAM" Member="SANPHAMs" ThisKey="IdDanhMuc" OtherKey="IdDanhMucSach" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.DATHANG" Member="DATHANGs">
    <Type Name="DATHANG">
      <Column Name="IdDatHang" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenKhach" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="SANPHAM_DATHANG" Member="SANPHAM" ThisKey="MaHang" OtherKey="IdSanPham" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="IdSanPham" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NhaXB" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ChiTietSach" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XuHuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IdDanhMucSach" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="SANPHAM_DATHANG" Member="DATHANGs" ThisKey="IdSanPham" OtherKey="MaHang" Type="DATHANG" />
      <Association Name="DANHMUCSP_SANPHAM" Member="DANHMUCSP" ThisKey="IdDanhMucSach" OtherKey="IdDanhMuc" Type="DANHMUCSP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>